# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js.yml CI workflow file

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        default: 'test'
        required: true

jobs:
  #First Job in same workflow
  Build_And_Deploy_Job:
    name: Build the solution and deploy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/
  
  #Second Job in same workflow file
  Testing_Job:
    runs-on: ubuntu-latest
    #Linking to previous job result 
    needs: Build_And_Deploy_Job
   
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-2016]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: webpack artifacts
        path: public

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
